export const budgetTypes = [
    { label: "Groceries", value: "Groceries" },
    { label: "Rent", value: "Rent" },
    { label: "Food", value: "Food" },
    { label: "Lunch", value: "Lunch" },
    { label: "Breakfast", value: "Breakfast" },
    { label: "Meal", value: "Meal" },
    { label: "Dinner", value: "Dinner" },
    { label: "Utilities", value: "Utilities" },
    { label: "Electric Bill", value: "Electric Bill" },
    { label: "Water Bill", value: "Water Bill" },
    { label: "Internet", value: "Wifi Bill" },
    { label: "Wifi Bill", value: "Internet" },
    { label: "Phone Bill", value: "Phone Bill" },
    { label: "Transportation", value: "Transportation" },
    { label: "Gas", value: "Gas" },
    { label: "Car Payment", value: "Car Payment" },
    { label: "Insurance", value: "Insurance" },
    { label: "Health Care", value: "Health Care" },
    { label: "Dining Out", value: "Dining Out" },
    { label: "Entertainment", value: "Entertainment" },
    { label: "Shopping", value: "Shopping" },
    { label: "Clothing", value: "Clothing" },
    { label: "Subscriptions", value: "Subscriptions" },
    { label: "Education", value: "Education" },
    { label: "Childcare", value: "Childcare" },
    { label: "Savings", value: "Savings" },
    { label: "Emergency Fund", value: "Emergency Fund" },
    { label: "Investments", value: "Investments" },
    { label: "Travel", value: "Travel" },
    { label: "Gifts", value: "Gifts" },
    { label: "Donations", value: "Donations" },
    { label: "Pets", value: "Pets" },
    { label: "Home Maintenance", value: "Home Maintenance" },
    { label: "Personal Care", value: "Personal Care" },
    { label: "Fitness", value: "Fitness" },
    { label: "Miscellaneous", value: "Miscellaneous" },
    { label: "Credit Card Payments", value: "Credit Card Payments" },
    { label: "Loan Payments", value: "Loan Payments" },
    { label: "Household Supplies", value: "Household Supplies" },
    { label: "Medical Expenses", value: "Medical Expenses" },
    { label: "Dental Care", value: "Dental Care" },
    { label: "Vision Care", value: "Vision Care" },
    { label: "Home Improvement", value: "Home Improvement" },
    { label: "Home Insurance", value: "Home Insurance" },
    { label: "Life Insurance", value: "Life Insurance" },
    { label: "Retirement Savings", value: "Retirement Savings" },
    { label: "Office Supplies", value: "Office Supplies" },
    { label: "Business Expenses", value: "Business Expenses" },
    { label: "Legal Fees", value: "Legal Fees" },
    { label: "Professional Services", value: "Professional Services" },
    { label: "Self-Care", value: "Self-Care" },
    { label: "Hobbies", value: "Hobbies" },
    { label: "Streaming Services", value: "Streaming Services" },
    { label: "Cloud Services", value: "Cloud Services" },
    { label: "Alimony", value: "Alimony" },
    { label: "Child Support", value: "Child Support" },
    { label: "Seasonal Expenses", value: "Seasonal Expenses" },
    { label: "Birthdays", value: "Birthdays" },
    { label: "Anniversaries", value: "Anniversaries" },
    { label: "Holidays", value: "Holidays" },
    { label: "Vacation Savings", value: "Vacation Savings" },
    { label: "Career Development", value: "Career Development" },
    { label: "Tuition Fees", value: "Tuition Fees" },
    { label: "Books & Supplies", value: "Books & Supplies" },
    { label: "Extracurricular Activities", value: "Extracurricular Activities" },
    { label: "Sports & Recreation", value: "Sports & Recreation" },
    { label: "Laundry", value: "Laundry" },
    { label: "Parking", value: "Parking" },
    { label: "Public Transportation", value: "Public Transportation" },
    { label: "Ride Sharing", value: "Ride Sharing" },
    { label: "Fuel", value: "Fuel" },
    { label: "Vehicle Maintenance", value: "Vehicle Maintenance" },
    { label: "Vehicle Insurance", value: "Vehicle Insurance" },
    { label: "Tolls", value: "Tolls" },
    { label: "Others", value: "Others" }
]