export const budgetTypes = [
    { label: "Groceries", value: "groceries" },
    { label: "Rent", value: "rent" },
    { label: "Food", value: "food" },
    { label: "Lunch", value: "lunch" },
    { label: "Breakfast", value: "breakfast" },
    { label: "Meal", value: "meal" },
    { label: "Dinner", value: "Dinner" },
    { label: "Utilities", value: "utilities" },
    { label: "Electric Bill", value: "electric_bill" },
    { label: "Water Bill", value: "water_bill" },
    { label: "Internet", value: "internet" },
    { label: "Phone Bill", value: "phone_bill" },
    { label: "Transportation", value: "transportation" },
    { label: "Gas", value: "gas" },
    { label: "Car Payment", value: "car_payment" },
    { label: "Insurance", value: "insurance" },
    { label: "Health Care", value: "health_care" },
    { label: "Dining Out", value: "dining_out" },
    { label: "Entertainment", value: "entertainment" },
    { label: "Shopping", value: "shopping" },
    { label: "Clothing", value: "clothing" },
    { label: "Subscriptions", value: "subscriptions" },
    { label: "Education", value: "education" },
    { label: "Childcare", value: "childcare" },
    { label: "Savings", value: "savings" },
    { label: "Emergency Fund", value: "emergency_fund" },
    { label: "Investments", value: "investments" },
    { label: "Travel", value: "travel" },
    { label: "Gifts", value: "gifts" },
    { label: "Donations", value: "donations" },
    { label: "Pets", value: "pets" },
    { label: "Home Maintenance", value: "home_maintenance" },
    { label: "Personal Care", value: "personal_care" },
    { label: "Fitness", value: "fitness" },
    { label: "Miscellaneous", value: "miscellaneous" },
    { label: "Credit Card Payments", value: "credit_card_payments" },
    { label: "Loan Payments", value: "loan_payments" },
    { label: "Household Supplies", value: "household_supplies" },
    { label: "Medical Expenses", value: "medical_expenses" },
    { label: "Dental Care", value: "dental_care" },
    { label: "Vision Care", value: "vision_care" },
    { label: "Home Improvement", value: "home_improvement" },
    { label: "Home Insurance", value: "home_insurance" },
    { label: "Life Insurance", value: "life_insurance" },
    { label: "Retirement Savings", value: "retirement_savings" },
    { label: "Office Supplies", value: "office_supplies" },
    { label: "Business Expenses", value: "business_expenses" },
    { label: "Legal Fees", value: "legal_fees" },
    { label: "Professional Services", value: "professional_services" },
    { label: "Self-Care", value: "self_care" },
    { label: "Hobbies", value: "hobbies" },
    { label: "Streaming Services", value: "streaming_services" },
    { label: "Cloud Services", value: "cloud_services" },
    { label: "Alimony", value: "alimony" },
    { label: "Child Support", value: "child_support" },
    { label: "Seasonal Expenses", value: "seasonal_expenses" },
    { label: "Birthdays", value: "birthdays" },
    { label: "Anniversaries", value: "anniversaries" },
    { label: "Holidays", value: "holidays" },
    { label: "Vacation Savings", value: "vacation_savings" },
    { label: "Career Development", value: "career_development" },
    { label: "Tuition Fees", value: "tuition_fees" },
    { label: "Books & Supplies", value: "books_supplies" },
    { label: "Extracurricular Activities", value: "extracurricular_activities" },
    { label: "Sports & Recreation", value: "sports_recreation" },
    { label: "Laundry", value: "laundry" },
    { label: "Parking", value: "parking" },
    { label: "Public Transportation", value: "public_transportation" },
    { label: "Ride Sharing", value: "ride_sharing" },
    { label: "Fuel", value: "fuel" },
    { label: "Vehicle Maintenance", value: "vehicle_maintenance" },
    { label: "Vehicle Insurance", value: "vehicle_insurance" },
    { label: "Tolls", value: "tolls" },
    { label: "Others", value: "others" }
]